### ISSUE TITLE
main does not build: E0004 non-exhaustive match on `SemanticAnnUnavailableReason` (missing `SessionScopeRequiresExact` arm), introduced in 01e22761

### ISSUE THREAD

**Issue by nskidan** [Dicklesworthstone/coding_agent_session_search#482]
Building `cass` from main fails at both 89b68592 and 30ac51c7 (tip as of 2026-09-18 ~05:30 UTC):

```
error[E0004]: non-exhaustive patterns: `SemanticAnnUnavailableReason::SessionScopeRequiresExact` not covered
   --> src/lib.rs:33885
note: enum defined at src/search/vector_index.rs:129
```

`git blame` places the new variant in 01e22761 ("fix(search): enforce session membership before semantic top-k", 2026-09-18 03:57 UTC, pushed by the automation account): it added the variant and its uses in `src/search/query.rs`, but the match in `src/lib.rs:33885` was not extended. The parent commit 607a9a11 builds clean with the same command.

Command: `cargo build --release --bin cass` with the repo's pinned nightly toolchain, on Linux x86-64. Build context: since frankensearch is pinned `=0.6.1` but crates.io only has 0.6.0 (the pending-release publication you mentioned on #479), I built with a local `[patch.crates-io]` pointing at the frankensearch repo's main — the E0004 is in this repo's own enum/match and independent of that patch. We are running 607a9a11 in the meantime.

**Comment by Dicklesworthstone** [comment]
Fixed directly on `main` in `ed7c3269198f551cda1a12447d7d9f0c8c9b32f1`, tracked by bead `coding_agent_session_search-gh482-ann-warning`.

The missing match arm now treats `SessionScopeRequiresExact` as intentional filtered exact search: the warning retains the stable `session_scope_requires_exact` code and explains that no index repair is needed. It does not recommend rebuilding HNSW or removing the session filter. The all-reasons test includes the new variant, and a dedicated regression checks this guidance.

**Full CASS compilation and the three real library tests now pass**, not just the initial standalone warning-function check. Run `35313711315`, job `105500872902`, compiled the complete CASS library test target and ran:

- `ann_fallback_human_warning_tests`: **3 passed, 0 failed**.
- `gh473`: **2 passed, 0 failed** (the earlier GH473 suites at this commit).
- `gh426_source_completion`: **1 passed, 0 failed**, including rollback and source-completion atomicity.

The only Rust warning was a pre-existing unused MetadataExt import in `src/daemon/client/exchange/tests.rs`. The E0004 error reported here is resolved.

**Dependency qualification scope:** this full-CASS build used an isolated, exact-revision source override of the intended same-version Frankensearch **0.6.1**, revision `2de4b7f529670c9aad1a676f9641210276aff1fb`, because that version is not yet available through the root registry graph. Its workspace family came from the same checkout. The real FrankenSQLite family remained registry **0.4.4**, and Asupersync remained registry **0.5.0**. No production manifest downgrade or committed lockfile rewrite was made. This proves the missing CASS match arm and its behavior are fixed; it is not registry-release or original-archive qualification.

Retained evidence artifact: `cass-candidate-evidence-35313711315` (ID `10535300008`), containing the test logs and both lockfiles. Candidate lock SHA-256: `c464a4ac5a2cbca2e0b53919e3024d47da3fddbd8bdcb9bc7bf7c19e1d7a1aed`.

**Comment by nskidan** [comment]
Confirmed on the reporting box: `cargo build --release --bin cass` at ed7c3269 completes with zero errors in the same environment that reproduced the E0004 (repo-pinned nightly; frankensearch `=0.6.1` still path-patched to its repo main since it remains unpublished on crates.io). We are keeping our timers on the 607a9a11 build validated earlier today (measurements on #479) and will move to the stock release when it ships. Thanks for the fast turnaround.
